module.exports = { origin: "africain", data: `
Alonyenkotab;b;noble;noble
Alonyenkotabi;g;noble;noble
Alonyenkotabik;b;noble;noble
Alonyenkotabika;g;noble;noble
Alonyenkotabike;g;noble;noble
Alonyenkotabikim;b;noble;noble
Alonyenkotabikin;b;noble;noble
Alonyenkotabiko;b;noble;noble
Alonyenkotabikoh;b;noble;noble
Alonyenkotabikoi;b;noble;noble
Alonyenkotabikoke;g;noble;noble
Alonyenkotabikol;b;noble;noble
Alonyenkotabikolam;b;noble;noble
Alonyenkotabikolan;b;noble;noble
Alonyenkotabikolar;b;noble;noble
Alonyenkotabikolars;b;noble;noble
Alonyenkotabikolas;b;noble;noble
Alonyenkotabikole;g;noble;noble
Alonyenkotabikoleh;g;noble;noble
Alonyenkotabikoli;g;noble;noble
Alonyenkotabikolim;b;noble;noble
Alonyenkotabikolin;b;noble;noble
Alonyenkotabikolina;g;noble;noble
Alonyenkotabikoline;g;noble;noble
Alonyenkotabikolini;g;noble;noble
Alonyenkotabikolink;b;noble;noble
Alonyenkotabikolip;b;noble;noble
Alonyenkotabikolipaz;b;noble;noble
Alonyenkotabikolipazo;b;noble;noble
Alonyenkotabikolipazon;b;noble;noble
Alonyenkotabikolipazor;b;noble;noble
Alonyenkotabikolipazos;b;noble;noble
Alonyenkotabikolipazot;b;noble;noble
Alonyenkotabikolipazotha;g;noble;noble
Alonyenkotabikolipazothah;g;noble;noble
Alonyenkotabikolipazothan;b;noble;noble
Alonyenkotabikolipazothar;b;noble;noble
Alonyenkotabikolipazothas;b;noble;noble
Alonyenkotabikolipazothash;b;noble;noble
Alonyenkotabikolipazothay;b;noble;noble
Alonyenkotabikolipazothayo;b;noble;noble
Alonyenkotabikolipazothe;g;noble;noble
Alonyenkotabikolipazotheh;g;noble;noble
Alonyenkotabikolipazothek;b;noble;noble
Alonyenkotabikolipazothekar;b;noble;noble
Alonyenkotabikolipazothekara;g;noble;noble
Alonyenkotabikolipazothekare;g;noble;noble
Alonyenkotabikolipazothekari;g;noble;noble
Alonyenkotabikolipazothekaro;b;noble;noble
Alonyenkotabikolipazothekaros;b;noble;noble
`};
