module.exports = { origin: "nordique", data: `
Alighilsonu;b;noble;noble
Alighilsonuk;b;noble;noble
Alighilsonukt;b;noble;noble
Alighilsonun;b;noble;noble
Alighilsonund;b;noble;noble
Alighilsonune;g;noble;noble
Alighilsonunh;b;noble;noble
Alighilsonunk;b;noble;noble
Alighilsonunkl;b;noble;noble
Alighilsonunkla;g;noble;noble
Alighilsonunkle;g;noble;noble
Alighilsonunkli;g;noble;noble
Alighilsonunklis;b;noble;noble
Alighilsonunklo;b;noble;noble
Alighilsonunklos;b;noble;noble
Alighilsonunkm;b;noble;noble
Alighilsonunkn;b;noble;noble
Alighilsonunko;b;noble;noble
Alighilsonunkob;b;noble;noble
Alighilsonunkoc;b;noble;noble
Alighilsonunkod;b;noble;noble
Alighilsonunkoe;b;noble;noble
Alighilsonunkof;b;noble;noble
Alighilsonunkog;b;noble;noble
Alighilsonunkoh;b;noble;noble
Alighilsonunkoi;b;noble;noble
Alighilsonunkok;b;noble;noble
Alighilsonunkol;b;noble;noble
Alighilsonunkolch;b;noble;noble
Alighilsonunkolcha;g;noble;noble
Alighilsonunkolche;g;noble;noble
Alighilsonunkolchi;g;noble;noble
Alighilsonunkolchim;b;noble;noble
Alighilsonunkolchin;b;noble;noble
Alighilsonunkolchio;b;noble;noble
Alighilsonunkolchis;b;noble;noble
Alighilsonunkolchit;b;noble;noble
Alighilsonunkolchith;b;noble;noble
Alighilsonunkolchu;b;noble;noble
Alighilsonunkolchun;b;noble;noble
Alighilsonunkolchur;b;noble;noble
Alighilsonunkolchus;b;noble;noble
Alighilsonunkolchut;b;noble;noble
Alighilsonunkold;b;noble;noble
Alighilsonunkolde;g;noble;noble
Alighilsonunkolf;b;noble;noble
Alighilsonunkolfe;g;noble;noble
Alighilsonunkolfi;g;noble;noble
Alighilsonunkolo;b;noble;noble
Alighilsonunkolob;b;noble;noble
`};
