module.exports = { origin: "portugais", data: `
Adunitieh;g;noble;noble
Adunitiei;g;noble;noble
Adunitieis;b;noble;noble
Adunitiek;b;noble;noble
Adunitiel;b;noble;noble
Adunitiele;g;noble;noble
Adunitieli;g;noble;noble
Adunitelik;b;noble;noble
Adunitelis;b;noble;noble
Adunifen;b;noble;noble
Adunifena;g;noble;noble
Adunifene;g;noble;noble
Adunifenea;g;noble;noble
Adunifenee;g;noble;noble
Adunifeneh;g;noble;noble
Adunifenei;g;noble;noble
Adunifeneik;b;noble;noble
Adunifeneim;b;noble;noble
Adunifenein;b;noble;noble
Adunifenek;b;noble;noble
Adunifenel;b;noble;noble
Adunifenela;g;noble;noble
Adunifenele;g;noble;noble
Adunifeneli;g;noble;noble
Adunifenelim;b;noble;noble
Adunifenelin;b;noble;noble
Adunifenelina;g;noble;noble
Adunifeneline;g;noble;noble
Adunifenelini;g;noble;noble
Adunifen;b;noble;noble
Adunifenelo;b;noble;noble
Adunifenelon;b;noble;noble
Adunifenelona;g;noble;noble
Adunifenelone;g;noble;noble
Adunifeneloni;g;noble;noble
Adunifenelons;b;noble;noble
Adunifenelop;b;noble;noble
Adunifenelops;b;noble;noble
Adunifenelopt;b;noble;noble
Adunifeneloptah;g;noble;noble
Adunifeneloptam;b;noble;noble
Adunifeneloptan;b;noble;noble
Adunifenelopte;g;noble;noble
Adunifeneloptem;b;noble;noble
Adunifeneloptemi;g;noble;noble
Adunifeneloptemia;g;noble;noble
Adunifenelopteno;b;noble;noble
Adunifeneloptenob;b;noble;noble
Adunifeneloptenoc;b;noble;noble
Adunifeneloptenod;b;noble;noble
`};
