module.exports = { origin: "slave", data: `
Allksandre;b;défenseur;defender
Allkse;g;noble;noble
Allksea;g;noble;noble
Allksei;b;défenseur;defender
Allkseia;g;noble;noble
Allkseik;b;noble;noble
Allksein;b;noble;noble
Allkseina;g;noble;noble
Allkseine;g;noble;noble
Allkseini;g;noble;noble
Allkseinis;b;noble;noble
Allkseink;b;noble;noble
Allkseinko;b;noble;noble
Allkseinm;b;noble;noble
Allkseinn;b;noble;noble
Allkseinnah;g;noble;noble
Allkseino;b;noble;noble
Allkseinos;b;noble;noble
Allkseins;b;noble;noble
Allkseinu;b;noble;noble
Allkseio;b;noble;noble
Allkseion;b;noble;noble
Allkseionk;b;noble;noble
Allkseionm;b;noble;noble
Allkseionn;b;noble;noble
Allkseionno;b;noble;noble
Allkseionnoh;b;noble;noble
Allkseionnok;b;noble;noble
Allkseionnom;b;noble;noble
Allkseionnor;b;noble;noble
Allkseionnos;b;noble;noble
Allkseionnot;b;noble;noble
Allkseionnou;b;noble;noble
Allkseionnov;b;noble;noble
Allkseionnovk;b;noble;noble
Allkseionnovs;b;noble;noble
Allkseionnovy;b;noble;noble
Allkseionr;b;noble;noble
Allkseions;b;noble;noble
Allkseionse;g;noble;noble
Allkseionsh;b;noble;noble
Allkseiont;b;noble;noble
Allkseionts;b;noble;noble
Allkseionu;b;noble;noble
Allkseiop;b;noble;noble
Allkseior;b;noble;noble
Allkseios;b;noble;noble
Allkseip;b;noble;noble
Allkseiq;b;noble;noble
Allkseir;b;noble;noble
`};
