module.exports = { origin: "slave", data: `
Allkseirs;b;noble;noble
Allkseirt;b;noble;noble
Allkseiru;b;noble;noble
Allkseiry;b;noble;noble
Allkseisa;g;noble;noble
Allkseis;b;noble;noble
Allkseish;b;noble;noble
Allkseiss;g;noble;noble
Allkseissa;g;noble;noble
Allkseissah;g;noble;noble
Allkseissak;b;noble;noble
Allkseissal;b;noble;noble
Allkseissam;b;noble;noble
Allkseissan;b;noble;noble
Allkseissana;g;noble;noble
Allkseissane;g;noble;noble
Allkseissang;b;noble;noble
Allkseissani;g;noble;noble
Allkseissanik;b;noble;noble
Allkseissanin;b;noble;noble
Allkseissaning;b;noble;noble
Allkseissanio;b;noble;noble
Allkseissanior;b;noble;noble
Allkseissanios;b;noble;noble
Allkseissanir;b;noble;noble
Allkseissanis;b;noble;noble
Allkseissanise;g;noble;noble
Allkseissanisha;g;noble;noble
Allkseissaniss;g;noble;noble
Allkseissanissa;g;noble;noble
Allkseissanit;g;noble;noble
Allkseissanita;g;noble;noble
Allkseissanite;g;noble;noble
Allkseissaniti;g;noble;noble
Allkseissanits;b;noble;noble
Allkseissank;b;noble;noble
Allkseissanka;g;noble;noble
Allkseissanke;g;noble;noble
Allkseissanki;g;noble;noble
Allkseissankim;b;noble;noble
Allkseissankin;b;noble;noble
Allkseissankins;b;noble;noble
Allkseissanko;b;noble;noble
Allkseissankob;b;noble;noble
Allkseissankoc;b;noble;noble
Allkseissankod;b;noble;noble
Allkseissankoe;b;noble;noble
Allkseissankof;b;noble;noble
Allkseissankog;b;noble;noble
Allkseissankoh;b;noble;noble
`};
