module.exports = {
  origin: "grec",
  names: [
    // Garçons
    { name: "Leandre", gender: "boy", fr: "Homme-lion", en: "Lion-man", tags: ["force", "courage"], style: ["elegant", "rare"] },
    { name: "Damien", gender: "boy", fr: "Qui dompte, dompteur", en: "To tame", tags: ["force"], style: ["classique"] },
    { name: "Stavros", gender: "boy", fr: "Croix", en: "Cross", tags: ["foi"], style: ["rare", "classique"] },
    { name: "Anastase", gender: "boy", fr: "Résurrection", en: "Resurrection", tags: ["foi", "espoir"], style: ["rare", "classique"] },
    { name: "Demetrios", gender: "boy", fr: "Dévoué à Déméter", en: "Devoted to Demeter", tags: ["nature", "foi"], style: ["rare", "classique"] },
    { name: "Evangelos", gender: "boy", fr: "Bonne nouvelle", en: "Good news", tags: ["espoir", "foi"], style: ["rare"] },
    { name: "Jason", gender: "boy", fr: "Guérisseur", en: "Healer", tags: ["sagesse", "espoir"], style: ["moderne", "classique"] },
    { name: "Lysandre", gender: "boy", fr: "Libérateur des hommes", en: "Liberator", tags: ["liberte", "force"], style: ["elegant", "rare"] },
    { name: "Orion", gender: "boy", fr: "Chasseur, constellation", en: "Hunter, constellation", tags: ["nature", "lumiere"], style: ["rare", "poetique"] },
    { name: "Hector", gender: "boy", fr: "Qui tient bon, défenseur", en: "Steadfast defender", tags: ["courage", "force"], style: ["classique", "rare"] },
    { name: "Achille", gender: "boy", fr: "Héros invincible", en: "Invincible hero", tags: ["force", "courage"], style: ["classique", "rare"] },
    { name: "Cosmas", gender: "boy", fr: "Ordre, univers", en: "Order, universe", tags: ["sagesse", "paix"], style: ["rare"] },
    { name: "Vassilis", gender: "boy", fr: "Roi", en: "King", tags: ["noblesse"], style: ["rare", "classique"] },
    { name: "Nikephoros", gender: "boy", fr: "Porteur de victoire", en: "Bearer of victory", tags: ["victoire"], style: ["rare"] },
    // Filles
    { name: "Daphne", gender: "girl", fr: "Laurier", en: "Laurel", tags: ["nature", "beaute"], style: ["elegant", "poetique"] },
    { name: "Cassandre", gender: "girl", fr: "Prophétesse, qui brille", en: "Prophetess, shining", tags: ["sagesse", "lumiere"], style: ["elegant", "rare"] },
    { name: "Penelope", gender: "girl", fr: "Tisserande, fidèle", en: "Weaver, faithful", tags: ["foi", "sagesse"], style: ["elegant", "classique"] },
    { name: "Calliope", gender: "girl", fr: "Belle voix", en: "Beautiful voice", tags: ["beaute", "joie"], style: ["rare", "poetique"] },
    { name: "Ariane", gender: "girl", fr: "Très sainte, pure", en: "Most holy", tags: ["grace", "noblesse"], style: ["elegant", "classique"] },
    { name: "Irene", gender: "girl", fr: "Paix", en: "Peace", tags: ["paix"], style: ["classique", "elegant"] },
    { name: "Thalia", gender: "girl", fr: "Florissante, joyeuse", en: "Flourishing, joyful", tags: ["joie", "nature"], style: ["rare", "poetique"] },
    { name: "Selene", gender: "girl", fr: "Lune", en: "Moon", tags: ["lumiere", "beaute"], style: ["elegant", "poetique"] },
    { name: "Iris", gender: "girl", fr: "Arc-en-ciel, messagère", en: "Rainbow, messenger", tags: ["beaute", "espoir"], style: ["court", "poetique"] },
    { name: "Theodora", gender: "girl", fr: "Don de Dieu", en: "Gift of God", tags: ["foi", "grace"], style: ["elegant", "rare"] },
    { name: "Phoebe", gender: "girl", fr: "Brillante, pure", en: "Bright, pure", tags: ["lumiere", "grace"], style: ["rare", "elegant"] },
    { name: "Melina", gender: "girl", fr: "Miel, douceur", en: "Honey, sweetness", tags: ["grace", "amour"], style: ["elegant", "poetique"] },
    { name: "Pandora", gender: "girl", fr: "Tous les dons", en: "All gifts", tags: ["grace", "beaute"], style: ["rare", "poetique"] },
    { name: "Niki", gender: "girl", fr: "Victoire", en: "Victory", tags: ["victoire"], style: ["court", "moderne"] },
    { name: "Anthea", gender: "girl", fr: "Fleurie, épanouie", en: "Flowery", tags: ["nature", "beaute"], style: ["rare", "poetique"] },
  ],
};
